---
title: "PSTAT122_Final"
format: pdf
editor: visual
---

```{r Libraries}
library(car)
library(emmeans)
library(tidyverse)
library(knitr)
```


```{r}
# randomizing assignments
set.seed(21)

text_settings <- c("black, small", "black, large", "red, small", "red, large")

treatments <- rep(text_settings, each = 4)

sample(treatments)
```

```{r}
# data
data <- read.csv("Final_Data.csv")

# get factors in their own columns
# font color levels: black (-), red (+)
# font size levels: small (-), large (+)

read_speed <- data |>
  mutate("Font Color" = str_detect(Text.Settings, "red, small") | str_detect(Text.Settings, "red, large"),
         "Font Size" = str_detect(Text.Settings, "black, large") | str_detect(Text.Settings, "red, large")) |>
  rename("Time" = Time..s.) |>
  select(`Font Color`, `Font Size`, `Time`)

read_speed$`Font Color` <- factor(read_speed$`Font Color`,
                                  levels = c(TRUE, FALSE),
                                  labels = c("Red", "Black"))

read_speed$`Font Size` <- factor(read_speed$`Font Size`,
                                 levels = c(TRUE, FALSE),
                                 labels = c("Large", "Small"))

kable(read_speed)
```

